# Generated by Django 5.2.15 on 2026-06-11 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('instagram_username', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Europe/Skopje', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=30)),
                ('instagram_username', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone call'), ('sms', 'SMS'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email')], default='viber', max_length=20)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='booking.salon')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_notice_days', models.PositiveSmallIntegerField(default=14)),
                ('maximum_booking_window_days', models.PositiveSmallIntegerField(default=60)),
                ('allow_same_day_booking', models.BooleanField(default=False)),
                ('allow_next_day_booking', models.BooleanField(default=False)),
                ('auto_approve_bookings', models.BooleanField(default=False)),
                ('late_arrival_limit_minutes', models.PositiveSmallIntegerField(default=15)),
                ('reminder_hours_before', models.PositiveSmallIntegerField(default=24)),
                ('pending_holds_slot', models.BooleanField(default=True)),
                ('pending_expiration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_appointments_per_day', models.PositiveSmallIntegerField(default=5)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=30)),
                ('buffer_minutes_between_bookings', models.PositiveSmallIntegerField(default=0)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policy', to='booking.salon')),
            ],
            options={
                'verbose_name_plural': 'booking policies',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('total_duration_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('source', models.CharField(choices=[('online', 'Online'), ('owner_manual', 'Owner manual'), ('instagram', 'Instagram'), ('messenger', 'Messenger'), ('viber', 'Viber'), ('phone', 'Phone'), ('in_person', 'In person')], default='online', max_length=20)),
                ('customer_note', models.TextField(blank=True)),
                ('owner_note', models.TextField(blank=True)),
                ('reference_photo', models.ImageField(blank=True, upload_to='booking_photos/')),
                ('rules_accepted', models.BooleanField(default=False)),
                ('rules_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('change_message_generated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.customer')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.salon')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('photo_recommended', models.BooleanField(default=False)),
                ('extra_duration_note', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.salon')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('duration_minutes_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_services', to='booking.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnavailableTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_time_blocks', to='booking.salon')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_working_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking.salon')),
            ],
            options={
                'verbose_name_plural': 'working hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='DateWorkingHoursOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('use_default', 'Use default working hours'), ('closed', 'Closed'), ('custom_hours', 'Custom working hours')], default='use_default', max_length=20)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_working_hours_overrides', to='booking.salon')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('salon', 'date'), name='unique_date_working_hours_override_per_salon')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('instagram_username', models.CharField(blank=True, max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_blocklist_entries', to='booking.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('salon', 'phone_number'), name='unique_active_blocked_phone_per_salon')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('salon', 'phone_number'), name='unique_customer_phone_per_salon'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'status', 'start_at'], name='booking_boo_salon_i_2ec926_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'start_at', 'end_at'], name='booking_boo_salon_i_179729_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('salon', 'name'), name='unique_service_name_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('salon', 'weekday'), name='unique_working_hours_weekday_per_salon'),
        ),
    ]
