# Generated by Django 6.0.4 on 2026-06-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_booking_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_display', models.CharField(help_text='e.g. "600", "+100/200", "1500-2000"', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='booking.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
