# Generated by Django 6.0.4 on 2026-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_service_price_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepriceitem',
            name='group',
            field=models.CharField(blank=True, help_text='Optional section heading, e.g. "Express treatments". Leave blank for ungrouped.', max_length=120),
        ),
    ]
