# Generated by Django 6.0.4 on 2026-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_price_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepriceitem',
            name='photo_required',
            field=models.BooleanField(default=False, help_text='Customer must upload a reference photo when booking this specific sub-service.'),
        ),
    ]
