# Generated by Django 6.0.4 on 2026-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_add_price_item_photo_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_approved',
            field=models.TextField(blank=True, default='Здраво {ime}, вашиот термин за {datum} во {vreme} е потврден. Ве очекуваме! — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Approved message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_cancelled',
            field=models.TextField(blank=True, default='Здраво {ime}, вашиот термин за {datum} во {vreme} е откажан. Ви благодариме на разбирањето. — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Cancelled message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_edited',
            field=models.TextField(blank=True, default='Здраво {ime}, вашиот термин е променет на {datum} во {vreme}. Ве очекуваме! — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Edited/rescheduled message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_no_show',
            field=models.TextField(blank=True, default='Здраво {ime}, не се јавивте на вашиот термин на {datum} во {vreme}. Доколку сакате да закажете нов термин, контактирајте нè. — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='No-show message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_pending',
            field=models.TextField(blank=True, default='Здраво {ime}, вашето барање за термин на {datum} во {vreme} е примено. Ќе ве контактираме наскоро. — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Pending/received message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_rejected',
            field=models.TextField(blank=True, default='Здраво {ime}, за жал терминот за {datum} во {vreme} не е достапен. Ве молиме изберете друг термин. — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Rejected message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='msg_reminder',
            field=models.TextField(blank=True, default='Здраво {ime}, ве потсетуваме дека имате термин на {datum} во {vreme}. Ве очекуваме! — {salon}', help_text='Variables: {ime} {datum} {vreme} {salon}', verbose_name='Reminder message'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='salon_rules',
            field=models.TextField(blank=True, default='Закажувањето е можно минимум 14 дена однапред.\nДоцнење повеќе од 15 минути без известување може да резултира со откажување на терминот.\nПри откажување, известете не најмалку 24 часа однапред.\nЗа одредени услуги е потребна референтна фотографија.', help_text='Rules shown to customers on the booking form. Each line becomes a separate rule bullet.'),
        ),
    ]
