# Generated by Django 5.2.15 on 2026-06-21 14:47

import booking.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_manage_token_and_customer_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='booking_rate_limit_per_email_per_day',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='booking_rate_limit_per_ip_per_hour',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='booking_rate_limit_per_phone_per_day',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='enable_honeypot_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='max_active_future_bookings_per_customer',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='max_pending_bookings_per_customer',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='max_reference_photo_size_mb',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference_photo',
            field=models.ImageField(blank=True, upload_to=booking.image_utils.booking_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='bookingactivitylog',
            name='action',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('customer_cancelled', 'Cancelled by customer'), ('edited', 'Edited'), ('completed', 'Completed'), ('no_show', 'No Show'), ('email_sent', 'Email sent')], max_length=30),
        ),
    ]
