# Generated by Django 5.2.15 on 2026-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_complete_and_calendar_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='business_category',
            field=models.CharField(choices=[('salon', 'Beauty salon'), ('barber', 'Barbershop'), ('sports', 'Sports venue'), ('fitness', 'Fitness / gym'), ('services', 'Services'), ('other', 'Other')], db_index=True, default='salon', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salon',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
