# Generated by Django 5.2.15 on 2026-07-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_salon_business_category_and_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='allow_last_minute_reopen',
            field=models.BooleanField(default=True, help_text='When enabled, cancelled or rejected appointments inside the minimum notice window become bookable online at the freed time only.'),
        ),
        migrations.CreateModel(
            name='ReleasedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_slots', to='booking.salon')),
                ('source_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_slots', to='booking.booking')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['salon', 'is_active', 'start_at'], name='booking_rel_salon_i_e775a6_idx')],
            },
        ),
    ]
