# Generated by Django 5.2.15 on 2026-07-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_released_slot_and_last_minute_toggle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerblocklist',
            options={'ordering': ['-blocked_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='client_device_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_blocks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocklist_entries', to='booking.customer'),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='device_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('fake_bookings', 'Fake bookings'), ('repeated_no_shows', 'Repeated no-shows'), ('repeated_cancellations', 'Repeated cancellations'), ('inappropriate_photos', 'Inappropriate photos'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='source_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_blocks', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='unblocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerblocklist',
            name='unblocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_blocks_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerBlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('updated', 'Updated')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocklist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.customerblocklist')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_block_events', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
