# Generated by Django 5.2.15 on 2026-07-02 15:06

from django.conf import settings
from django.db import migrations, models


def backfill_blocklist_blocked_at(apps, schema_editor):
    CustomerBlocklist = apps.get_model("booking", "CustomerBlocklist")
    for entry in CustomerBlocklist.objects.filter(blocked_at__isnull=True):
        entry.blocked_at = entry.created_at
        entry.save(update_fields=["blocked_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_customer_blocking_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_blocklist_blocked_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='customerblocklist',
            index=models.Index(fields=['salon', 'is_active'], name='booking_cus_salon_i_35a69c_idx'),
        ),
        migrations.AddIndex(
            model_name='unavailabletimeblock',
            index=models.Index(fields=['salon', 'date'], name='booking_una_salon_i_0637a4_idx'),
        ),
    ]
