# Generated by Django 5.2.15 on 2026-07-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_production_indexes_and_blocklist_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='fixed_start_times',
            field=models.JSONField(blank=True, default=list, help_text='List of HH:MM start times, e.g. 08:00, 10:30, 13:00, 15:30.', verbose_name='Fixed start times'),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='use_fixed_start_times',
            field=models.BooleanField(default=False, help_text='When enabled, customers can only book at the configured start times. Slot interval is ignored.', verbose_name='Use fixed start times'),
        ),
    ]
