# Generated by Django 5.2.15 on 2026-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_customer_optional_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
