# Generated by Django 5.2.15 on 2026-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_servicepriceitem_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Optional Google Maps (or other maps) link. If set, the public Pro/Premium page uses this for Open in Maps. Useful when you have a Maps link but not a full street address.', max_length=500),
        ),
    ]
