# Generated by Django 5.2.15 on 2026-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_salon_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepriceitem',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='Optional extra on top of a main (base) sub-service. Leave off for normal standalone choices.'),
        ),
    ]
