# Generated by Django 5.2.15 on 2026-08-12 20:29

from django.db import migrations, models


def repair_addon_duration_snapshots(apps, schema_editor):
    """Fix add-on lines that wrongly inherited the full parent service duration.

    BookingService.save() used to treat duration 0 as missing and overwrite it
    with service.duration_minutes, so extras like French showed as a second
    2-hour slot in emails/schedules even when total_duration stayed correct.
    """
    BookingService = apps.get_model("booking", "BookingService")
    ServicePriceItem = apps.get_model("booking", "ServicePriceItem")

    addon_items = ServicePriceItem.objects.filter(is_addon=True).only(
        "id", "service_id", "name", "duration_minutes"
    )
    addons_by_key = {}
    for item in addon_items:
        addons_by_key[(item.service_id, item.name)] = item

    for bs in BookingService.objects.select_related("service").iterator():
        item = addons_by_key.get((bs.service_id, bs.service_name_snapshot))
        if item is None:
            continue
        correct = item.duration_minutes or 0
        updates = {}
        if not bs.is_addon_snapshot:
            updates["is_addon_snapshot"] = True
        if bs.duration_minutes_snapshot != correct:
            updates["duration_minutes_snapshot"] = correct
        if updates:
            BookingService.objects.filter(pk=bs.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0026_servicepriceitem_is_addon"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="is_addon_snapshot",
            field=models.BooleanField(
                default=False,
                help_text="True when this line was booked as an add-on extra, not a base service.",
            ),
        ),
        migrations.RunPython(repair_addon_duration_snapshots, noop_reverse),
    ]
